name: Main

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: "Main"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm
      - name: install
        run: npm ci || npm install
      - name: Build
        env:
          VITE_SSE_URL: ${{ secrets.VITE_SSE_URL }}
        run: npm run build
      - name: Pack
        run: npm run zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: FastTTD.zip
permissions:
  contents:
    write

    # - name: Release
    #   uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: ""
    #     prerelease: true
    #     title: "Pre-release Build"
    #     files: FastTTD.zip
